# Generated by Django 2.2.7 on 2019-11-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drones',
            options={'verbose_name': 'Drone', 'verbose_name_plural': 'Drones'},
        ),
        migrations.RemoveField(
            model_name='drones',
            name='longtitude',
        ),
        migrations.AddField(
            model_name='drones',
            name='longitude',
            field=models.FloatField(default=35, verbose_name='longitude'),
            preserve_default=False,
        ),
    ]
