# Generated by Django 2.2.7 on 2019-11-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0002_auto_20191117_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drones',
            name='latitude',
            field=models.FloatField(blank=True, verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='drones',
            name='longitude',
            field=models.FloatField(blank=True, verbose_name='longitude'),
        ),
    ]
