# Generated by Django 2.2.7 on 2019-11-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0003_auto_20191117_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drones',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='drones',
            name='longitude',
        ),
        migrations.AddField(
            model_name='drones',
            name='drone_id',
            field=models.PositiveIntegerField(default=1, verbose_name='Drone number'),
            preserve_default=False,
        ),
    ]
