# Generated by Django 2.2.7 on 2019-11-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0004_auto_20191117_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drones',
            name='drone_id',
            field=models.PositiveIntegerField(unique=True, verbose_name='Drone number'),
        ),
    ]
